// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52Nr0m3-4e5ehiOBosTvgJjg8i_EPUEM',
    appId: '1:426822002002:web:c1328ca59bd4d0dcb2068b',
    messagingSenderId: '426822002002',
    projectId: 'vetclick-b41a6',
    authDomain: 'vetclick-b41a6.firebaseapp.com',
    storageBucket: 'vetclick-b41a6.firebasestorage.app',
    measurementId: 'G-BPYCC0YE47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBacqagNXw9bClCKeWmEIah4P_X7Ih97DM',
    appId: '1:426822002002:android:a341eb5185d88e11b2068b',
    messagingSenderId: '426822002002',
    projectId: 'vetclick-b41a6',
    storageBucket: 'vetclick-b41a6.firebasestorage.app',
  );
}
